name: Create Release PR

on:
  push:
    branches:
      - 'release/v*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: main
          title: "Release ${{ github.ref_name }}"
          body: |
            This PR was created automatically by release-it.
            It bumps the version and prepares the release.
